### ISSUE TITLE
MLE fit with kernel>1

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#13]
Open test2.sdt
Analyze>Lifetime>FLIMJ
Enter Time Bin (ns) = 0.039, click OK
Set Kernel Size = 2 or 3
Set Noise Model = MLE
Click Fit Dataset

Result: Processing takes longer than usual

Change Show to tau

Result: Result image shows one color (green) and scale bar = 0 for kernel=2, or extreme values and colors for kernel=3. Looks like many or sometimes all pixels are failing to fit and are given the tau value of zero.

Compare with:
MLE with kernel = 1
Any other noise model and kernel = 2 or 3

tested on flimj-ui-1.0.7

**Comment by Xanthorapedia** [comment]
The problem seems to be caused by binning. Here is what I found out:
- The binning before dataset fitting is done by `ops.filter().convolve()`, which internally uses FT and IFT. For pixels whose neighbors are 0 within 2-3 pixels, `convolve()` may spit out a very small (~1e-6) negative value. - _This explains why it only happens to dataset fitting. Single-pixel preview bins with brute force._
- This causes [`logf()` in e.g. `GCI_marquardt_compute_fn()`](https://github.com/flimlib/flimlib/blob/e88bb7292b7cc9cdc5daebcd5e03b9cd51247ebb/src/main/c/EcfSingle.c#L1129) to take a negative input and output `NaN`, which contaminates chisq. - _This explains why it only happens to MLE._
- When determining if the fit meets the [chisq stopping condition](https://github.com/flimlib/flimlib/blob/e88bb7292b7cc9cdc5daebcd5e03b9cd51247ebb/src/main/c/EcfSingle.c#L694-L699), it thinks chisq never improved (any comparison involving `NaN` gives `false`). And keeps fitting until it gives up at `MAXITERS` iterations. - _This explains why the fit takes longer._
- While compiling results in fitting ops, a returned chisq of value `NaN` is seen as a sign of bad fit. The results are therefore dropped.

The fix is simply clamping trans values above 0 after `convolve()`.

Results (kernel size = 2):
![image](https://user-images.githubusercontent.com/25558041/87885276-630be980-c9da-11ea-877d-378230aa9d7c.png)
(Left: before; Right: now)

Thank you for catching this problem!
