### ISSUE TITLE
Unexpected Intensity Thresh. Behaviour

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#14]
Open test2.sdt
Analyze>Lifetime>FLIMJ
Enter Time Bin (ns) = 0.039, click OK
Set Intensity Thresh. = 100
Click Fit Dataset and wait
Set Show to tau as Color

Result: Appears that no pixels have been processed on image and scale bar.

In Export, set Images to tau
Click Export

Result: See that pixels have been processed and have a non-zero value in the image exported into Fiji.

Compare with: Intensity Thresh. = 50

tested on flimj-ui-1.0.7

**Comment by Xanthorapedia** [comment]
> Result: Appears that no pixels have been processed on image and scale bar.

This seems to be caused by both the min and max being set to 0. I have been struggling with picking a proper min and max for the color bar as the values (especially tau) vary a lot if there are bad fits. The current strategy is to pick min to be the 10th percentile among all pixels and max to be the 90th, meaning if the majority of the values are 0, both limits are zeroed as well. @paulbarber @JenuC Suggestions on how to pick a "good" limit?

> Result: See that pixels have been processed and have a non-zero value in the image exported into Fiji.

I <kbd>Shift</kbd>+<kbd>C</kbd>-ed the exported tau image. Seems like Fiji automatically fixes degenerate LUTs by simply setting the min and max to the extrema of the dataset. The discrepancy will go away whenever we set a proper limit fo the LUT.

**Comment by paulbarber** [comment]
OK, setting the limits for the LUT is not easy. I have a algorithm in TRI2 similar to what you describe, but I do exclude all the zero pixels (invalid lifetime/not calculated pixels) and set the range on the rest. That will help. @Xanthorapedia

**Comment by JenuC** [comment]
I agree with Paul. hardcoded limits for the LUT scale to 10-90% would not work on all images. In my experience, I have used more in the range of 60-99% of non-zero pixels. but my experiments are mostly single-cell and won't translate to a larger FLIM community. Just saying these values are variable and users may have their own preference. But, this is interesting. @Xanthorapedia Could you please send me a script for generating the pseudo-color-coded image? we can add it to the groovy markdown file so that users have an option to change lifetime LUT-range of intensity LUT-range as they prefer.  Then you can set the LUT to 1-100 of non-zero values in the UI and let users choose the groovy route for custom dynamic ranges.

**Comment by Xanthorapedia** [comment]
> Could you please send me a script for generating the pseudo-color-coded image? we can add it to the groovy markdown file so that users have an option to change lifetime LUT-range of intensity LUT-range as they prefer.

@JenuC Sure. We actually have an Op for this purpose. So if you go to the Utility Code section of [the demo notebook](https://github.com/flimlib/flimj-ops/blob/ef1efc05d7cbdcc4a9e917579b605545723f42b6/notebooks/Demo.ipynb), you will see a line saying
```groovy
def pseudocolor = op.run("flim.showPseudocolor", fitted, tMin, tMax, 0, aMax);
```
You can just throw in `results.paramMap` and min, max for tau, A and z (all optional, same default-value strategy as discussed above) to render the result into a multi-layer `Img<ARGBType>`. This API is far from perfect. So please file an issue in `flimj-ops` if you think we can somehow make it more usable.

**Comment by JenuC** [comment]
@Xanthorapedia : Thank you so much. 
i see this function:
```groovy 
op.transform().hyperSliceView(pseudocolor, lifetimeAxis, i)
```
[javadoc](https://javadoc.scijava.org/ImageJ/net/imagej/ops/transform/hyperSliceView/IntervalHyperSliceView.html#constructor.detail)

Pardon my trivial questions, but I can't figure out what this view function does in terms of image transform. Is it plotting intensity as an alpha layer over the lifetime-image? I would also like to use custom LUT in this pseudo-colored image (if that is possible without a lot of trouble).

**Comment by Xanthorapedia** [comment]
> Is it plotting intensity as an alpha layer over the lifetime-image?

@JenuC Thanks for bringing this up. `hyperSliceView()` chops out a slice from a high-dimensional image by fixing one coordinate at a location. It is used here because the rendered parameter images returned from `flim.showPseudocolor` are stacked along the lifetime dimension. The rendering is done by first using the LUT to convert values into colors and then multiply each channel with the grayscale color (converted to with an grasca value of the intensity to darken less bright pixels.

> I would also like to use custom LUT in this pseudo-colored image (if that is possible without a lot of trouble).

Sure. The `flim.showPseudocolor` was designed to only handle `FitResult` objects, but a trick you can do is:

- Create a `FitResult`;
- Set `result.paramMap` to the image to be LUT-ed;
- Set `result.intensityMap` to the intensity image.

Make sure both images are 3-D and have the same shape (convert to `WxHx1` with [`Views.addDimension(image, 0, 0)`](https://javadoc.scijava.org/ImgLib2/net/imglib2/view/Views.html#addDimension-net.imglib2.RandomAccessibleInterval-long-long-) if you have a 2-D image) and set `result.ltAxis` to the extra dimension (2 in this case).

You may also want to set the `cMin`, `cMax`, `bMin` and `bMax` parameters to specify the range of values being colored and used  as the intensity.

**Comment by JenuC** [comment]
thanks. I will pursue this at a later stage.
