### ISSUE TITLE
Missing documentation of GUI - parameters

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ui#3]
Documentation for the GUI parameters is necessary. 

- Default Intensity threshold = -1 is not clear. How do we fit 0 photons?

- What does the two circles on the vertical bar in the plot window represent? Are there listeners implemented for that?

- There is a warning issued when the GUI loads.
```code 
Apr 09, 2020 12:38:54 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.172
```

- This exception keeps popping up when parameters are changed.

```code 
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at flimlib.flimj.ui.controller.PlotCtrl.plotFit(PlotCtrl.java:479)
	at flimlib.flimj.ui.controller.PlotCtrl.lambda$1(PlotCtrl.java:155)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Xanthorapedia** [comment]
> * Default Intensity threshold = -1 is not clear. How do we fit 0 photons?

Will change initial value to 5th percentile intensity of all pixels, if that sounds good.

> * What does the two circles on the vertical bar in the plot window represent? Are there listeners implemented for that?

Those are for you to drag the cursers more easily since the line cursers are too thin. The circle's positions along the line don't do anything.

> * There is a warning issued when the GUI loads.
> 
> ```
> Apr 09, 2020 12:38:54 PM javafx.fxml.FXMLLoader$ValueElement processValue
> WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.172
> ```

This is due to the fact that the layout xmls are written for JFX in Java 11 but we are using Java 8. The reason for using a newer xml version is that we may switch to newer Java later on. The warning can be safely ignored as long as we only use the Java 8-compatible part of the API.

> * This exception keeps popping up when parameters are changed.
> 
> ```
> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
> 	at flimlib.flimj.ui.controller.PlotCtrl.plotFit(PlotCtrl.java:479)
> 	at flimlib.flimj.ui.controller.PlotCtrl.lambda$1(PlotCtrl.java:155)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
> 	at java.lang.Thread.run(Thread.java:748)
> ```

Can you locate the version of the UI you are using? The version number is in the `<FIJI_directory>/jars/flimj-ui-*.jar` name.

> Why does chi-2 value have a variable target parameter?

This is a stopping condition of the fit from FLIMLib. The fitting will stop if chi-squared drops below the target.

**Comment by JenuC** [comment]
- 5th percentile: It is better to keep it fixed to zero instead. The dynamic range for FLIM files is too arbitrary based on the detector. There is no logical reason to select 5%. 
- all other concerns are sorted out.
